version: '3'

services:
  ci-build:
    image: microsoft/dotnet:2.0.0-sdk
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./WebInterface.sln && dotnet publish ./WebInterface.sln -c Release -o ./obj/Docker/publish"
