version: '3'

services:
  webinterface:
    image: webinterface
    container_name: webinterface
    build:
      context: ./WebInterface
      dockerfile: Dockerfile
#    networks:
#      - iiasa
#    external_links:
#      - geonode_geonode_1
    ports:
      - "5000:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

#networks:
#  default:
#    name: "iiasa_default"
#  default:
#    external: 
#      name: geonode_default